### ISSUE TITLE
Validation Not Working Propely On ngRepeat

### ISSUE THREAD

**Issue by rajan-logiciel** [huei90/angular-validation#127]
if we use validator with in ngRepeat then its Not working properly it 
Its perform validation at last input..... What is the solution of it??

See the example :-
http://plnkr.co/edit/1PwcjDOyXuQBUEA8N6J7?p=preview

**Comment by hungdoan2** [comment]
Hi Kumar, 
I which version of "angular-validation" did you test with ?.

I think you are using angular js 1.2.x and angular-validation 1.3.x

So that's the reason your test case was fail.

If you include angular 1.3.x version in your code. It will work perfectly fine.

p/s: to @huei90  Your library is so great. But  the most confused thing when I work with your lib is versioning . It's hard to figure out which version I'm using.

**Comment by huei90** [comment]
Thanks @hungdoan2 

You are right, it's quite confuse because the version 1.2.x and 1.3.x ...

It depends on the angular version you are using.

**Comment by rajan-logiciel** [comment]
Yeah... Its working fine with angular 1.3.x
thanks  @hungdoan2

**Comment by huei90** [comment]
:+1:
