### ISSUE TITLE
Validation Group and form checkValid

### ISSUE THREAD

**Issue by dapriett** [huei90/angular-validation#210]
Hello,

It looks like checkValid for a form returns false unless everything in the validation group is valid.  You can see this in your example by only selecting 1 checkbox https://github.com/huei90/angular-validation/blob/master/index.html#L325

Shouldn't the form be valid if at least one is selected?

**Comment by huei90** [comment]
Thank you for reporting this issue @dapriett 🍻

**Comment by huei90** [comment]
@lvarayut Do you have time to look at this?

**Comment by lvarayut** [comment]
I'll take a look at it as soon as possible, probably at the end of next week. Before that, if anybody could get it done, that would be really welcomed.

**Comment by dapriett** [comment]
Thank you!  Any plans to push a new release - looks like 1.4.1 is still the latest.

**Comment by lvarayut** [comment]
@huei90, I think that it's better to get the #212 done before releasing a new version.

**Comment by huei90** [comment]
agree.

**Comment by mooyoul** [comment]
It seems broken again 😢 

I just tested on **Form ($submit-only)** section on [example page](http://huei90.github.io/angular-validation/#examples).

It seems validation passed okay when checks any checkbox, but `checkValid` remains `false` even i entered **ALL** input items. **there are no invalid messages, or indicators**. it won't trigger `ng-click` handler with `validation-submit` directive combo too.

I'm guessing the root cause of this issue was from `NgModelController` of *unchecked* checkboxes.
`$valid` property of `NgModelController` were set to `false` even there are `validation-group` directive exists.
this makes parent `FormController.$valid` to `false`.
